FROM powerapi/powerapi:pypy-1.0.0
USER root
RUN apt update && apt upgrade -y
RUN apt install -y libblas-dev liblapack-dev libatlas-base-dev gfortran
USER powerapi
COPY --chown=powerapi . /tmp/smartwatts

RUN cd /tmp/smartwatts && \
	wget https://raw.githubusercontent.com/powerapi-ng/powerapi-ci-env/main/to_36.sh && \
	/bin/bash to_36.sh smartwatts

RUN pypy3 -m pip install --user --no-cache-dir "/tmp/smartwatts" && rm -r /tmp/smartwatts

ENTRYPOINT ["pypy3", "-m", "smartwatts"]
